apiVersion: v1
kind: ConfigMap
metadata:
  name: gopher-config
  namespace: default
data:
  LOG_FILE_PATH: "/var/log/pods/default_busybox-app/busybox/0.log"
  STATE_FILE_PATH: "/tmp/gopher-tailer.state"
  LOKI_URL: "http://loki-service:3100/loki/api/v1/push"